spring:
  application:
    name: studynotion-modern-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/studynotion
      database: studynotion
      authentication-database: admin
      username: root
      password: root
