spring:
  application:
    name: studynotion-modern-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/studynotion
      database: studynotion
      authentication-database: admin
      username: root
      password: root
  mail:
    host: smtp.yourprovider.com
    port: 587
    username: your_email@example.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: ${CLOUD_NAME:demo-cloud}
  api_key: ${API_KEY:demo-key}
  api_secret: ${API_SECRET:demo-secret}

jwt:
  secret: "${JWT_SECRET:myVerySecretKeyThatShouldBeAtLeast256BitsLongForHS256Algorithm2024SecureTokenGeneration}"
  expiration: 86400000

razorpay:
  key: ${RAZORPAY_KEY:your_razorpay_key}
  secret: ${RAZORPAY_SECRET:your_razorpay_secret}