spring:
  application:
    name: studynotion-modern-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/studynotion
      database: studynotion
      authentication-database: admin
      username: root
      password: root
  mail:
    host: smtp.yourprovider.com
    port: 587
    username: your_email@example.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
